config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :cart_items

  namespace :admin do
      get 'product/update_subcategories', as: 'update_subcategories'
      resources :users
      resources :categories
      resources :products 
      root to: "users#index"
      
    end
  
  devise_for :users
 root 'pages#home'
  resources :categories
 resources :products   
end

app/models/article.rb
 class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end 

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy


    def add_product(product, quantity)
  
      current_item = LineItem.find_by(product_id: product.id)
      if current_item
          current_item.quantity = current_item.quantity.to_i + quantity.to_i
      else
          current_item = line_items.build(product_id: product.id, quantity: quantity)
      end
      current_item
    end
      

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord
    
   has_many :subcategories, class_name: "Category", foreign_key: "parent_id"
   belongs_to :parent, class_name: "Category", optional: true

   has_many :product_categories, dependent: :destroy
   has_many :products, through: :product_categories

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart

    def total_price
        product.price.to_i * quantity.to_i
    end

end

app/models/message.rb
  class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
  end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

    before_destroy :not_referenced_by_any_line_item
    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories

    has_many :line_items
    mount_uploader :image, ImageUploader
    serialize :image, JSON


    validates :title, presence: true
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :brand, presence: true 
    validates :model, presence: true 
    validates :finish, presence: true
    validates :condition, presence: true
    validates :price, presence: true
    validates :quantity, presence: true

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            error.add(:base, "Line Items Present")
            throw :abort
        end    
    end   

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    belongs_to :product
    belongs_to :category

    
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true
    
    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: ENV["pusher_key"],
                                         secret_token: ENV["pusher_secret"],
                                                  endpoint: 'https://sandbox.iexapis.com/v1')
        begin
        new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
        return nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  

    def show
      @cart = Cart.find(params[:id])
    end

    
    def destroy
      @cart.destroy if @cart.id == session[:cart_id]
      session[:cart_id] = nil
      flash[:notice] = "Cart was successfully destroyed."
      redirect_to root_path
      
    end
    
  private

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<div class="container">
  <h3>Shopping Cart</h3>
  <div class="keep-shopping mt-4 mb-4 another-element">
    <%= link_to 'Keep shopping', products_path, class: "btn btn-warning" %>
  </div>

  <section class="section">
    <table  class="table is-narrow br">
    <thead>
    <tr>
      <th scope="col-2">Item</th>
      <th scope="col">Title</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Subtotal</th>
    </tr>
    </thead>  
    <tbody>
      <%= render(@cart.line_items) %>
    </tbody>
    </table>
    <div class="container">
    <div class="col">
      <div class="btn-group">
        <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        <%= button_to 'checkout', '#', class: "btn btn-secondary element" %>  
      </div>

      <div class="col another-element">
      <%#= button_to 'checkout', '#', class: "btn btn-secondary" %>  
      </div>
      
      <div class="col  another-element">
        <h4 class="title is-4 mt-4">
          <span class="text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
        </h4>
      </div>
    </div>
    </div>
  </section>
</div>