config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :cart_items

  namespace :admin do
      get 'product/update_subcategories', as: 'update_subcategories'
      resources :users
      resources :categories
      resources :products 
      root to: "users#index"
      
    end
  
  devise_for :users
 root 'pages#home'
  resources :categories
 resources :products   
end

app/models/article.rb
 class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end 

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy


    def add_product(product, quantity)
  
      current_item = LineItem.find_by(product_id: product.id)
      if current_item
          current_item.quantity = current_item.quantity.to_i + quantity.to_i
      else
          current_item = line_items.build(product_id: product.id, quantity: quantity)
      end
      current_item
    end
      

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord
    
   has_many :subcategories, class_name: "Category", foreign_key: "parent_id"
   belongs_to :parent, class_name: "Category", optional: true

   has_many :product_categories, dependent: :destroy
   has_many :products, through: :product_categories

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart

    def total_price
        product.price.to_i * quantity.to_i
    end

end

app/models/message.rb
  class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
  end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

    before_destroy :not_referenced_by_any_line_item
    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories

    has_many :line_items
    mount_uploader :image, ImageUploader
    serialize :image, JSON


    validates :title, presence: true
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :brand, presence: true 
    validates :model, presence: true 
    validates :finish, presence: true
    validates :condition, presence: true
    validates :price, presence: true
    validates :quantity, presence: true

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            error.add(:base, "Line Items Present")
            throw :abort
        end    
    end   

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    belongs_to :product
    belongs_to :category

    
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true
    
    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: ENV["pusher_key"],
                                         secret_token: ENV["pusher_secret"],
                                                  endpoint: 'https://sandbox.iexapis.com/v1')
        begin
        new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
        return nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    
    def index
      @category = Category.all
      # @categories = Category.find(:all, :conditions => {:parent_id => nil})
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
      @categories = Category.where(parent_id: nil)
    end

    
    def edit
      @category = Category.find(params[:id])
      @categories = Category.where(parent_id: nil)
    end


    def update
      @category = Category.find(params[:id])
      if @category.update(params.require(:category).permit(:name, :s_description, :l_description, :parent_id))
        flash[:notice] = "Category was successfully updated."
        redirect_to admin_category_path(@category)
      else
        render 'edit'  
      end 
    end


    def create
      @category = Category.new(params.require(:category).permit(:name, :s_description, :l_description, :parent_id))

      if @category.save
        flash[:notice] = "Category was successfully created."
        redirect_to admin_categories_path(@category)
      else
        render 'new'
      end
    end

    def destroy
      
      @category = Category.find(params[:id])
     
      @category.destroy
      flash[:notice] = " Category was succesfully deleted."
      redirect_to admin_categories_path
    end


  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def new
    end

    def create
    end

    def edit
    end
 
    def update
    end
    
    def index
        @categories = Category.all
    end
 
    def show
        
        @category = Category.find(params[:id])
        # @category.products
        # debugger
       
    end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info color: black" %> 

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-outline-light btn-lg mt-3" %>
  </div>
<% end %> 


<style>
.btn-lg{
  width: 200px;
}
</style>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="container">
    
    <div class="row justify-content-md-center">
    
        <% @categories.each do |category| %>
            <div class="card text-white bg-dark mb-3" style="width: 12rem;" id="card-styl"   >
                <div class="card-body">
                    <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-white" %></h5>
                </div>
            </div>
        <% end %>  
     
     
    </div>

</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3 text-center">
      <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= @category.name %> Products </h1>

<div class="container">
  <div class="row">
        <div class="row justify-content-md-center">
        <% @category.products.each do |category| %>
            <div class="card text-center shadow mb-5 bg-white rounded" style="width: 20rem"  id="card-styl">
                
              <div class="card-body">
              <% if category.image.present? %> 
             
                <%= link_to product_path(category) do %>
                <%= image_tag(category.image_url, class: "img-resm") %>
                <% end %>
              <% else %>
                Looks like you don't have any images uploaded!   
              <% end %>
              </div>

              <div class="card-body">
                <h3><%= category.title %> </h3> 
                <%#= category.description%>
                <div class="container"><strong><%= number_to_currency( category.price ) %></strong>

                <%#= form_with(model: Product.new , url: cart_items_path(product_id: category), class: "mb-2") do |form| %>
                <div><%#= button_to ("<i class='fa fa-cart-plus mr-2'></i> Add to cart").html_safe, cart_items_path, class: "btn btn-warning" %></div>
                <%# end %>

                </div>
              </div>
            </div>
        <% end %>  
    
    </div>
        
      </div>
    </div>
  
</div>



<script>
console.log("123");
console.log("234567");

  $(function(){
         alert("Category Show Page");
    });

</script>