config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :cart_items

  namespace :admin do
      get 'product/update_subcategories', as: 'update_subcategories'
      resources :users
      resources :categories
      resources :products 
      root to: "users#index"
      
    end
  
  devise_for :users
 root 'pages#home'
  resources :categories
 resources :products   
end

app/models/article.rb
 class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end 

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy


    def add_product(product, quantity)
  
      current_item = LineItem.find_by(product_id: product.id)
      if current_item
          current_item.quantity = current_item.quantity.to_i + quantity.to_i
      else
          current_item = line_items.build(product_id: product.id, quantity: quantity)
      end
      current_item
    end
      

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord
    
   has_many :subcategories, class_name: "Category", foreign_key: "parent_id"
   belongs_to :parent, class_name: "Category", optional: true

   has_many :product_categories, dependent: :destroy
   has_many :products, through: :product_categories

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart

    def total_price
        product.price.to_i * quantity.to_i
    end

end

app/models/message.rb
  class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
  end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

    before_destroy :not_referenced_by_any_line_item
    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories

    has_many :line_items
    mount_uploader :image, ImageUploader
    serialize :image, JSON


    validates :title, presence: true
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :brand, presence: true 
    validates :model, presence: true 
    validates :finish, presence: true
    validates :condition, presence: true
    validates :price, presence: true
    validates :quantity, presence: true

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            error.add(:base, "Line Items Present")
            throw :abort
        end    
    end   

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    belongs_to :product
    belongs_to :category

    
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true
    
    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: ENV["pusher_key"],
                                         secret_token: ENV["pusher_secret"],
                                                  endpoint: 'https://sandbox.iexapis.com/v1')
        begin
        new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
        return nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  before_action :set_line_item, only: %i[ show edit update destroy ]

  def create
    
  end
  
  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
    
    def line_item_params
      params.require(:line_item).permit(:quantity,:product_id, :cart_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div class="container">
<section>
  <table  class="table is-narrow br">
 
    <tbody>
    <tr>
      <td>  
        <div class="card" style="width: 5rem;">
          <% if line_item.product.image.present? %> 
              <%= image_tag(line_item.product.image_url, class: "img-resm") %>
          <% else %>
              No Image there    
          <% end %>
        </div>
      </td>
      <td><%= line_item.product.title %></td>
      <td><%= number_to_currency(line_item.product.price) %></td>
      <td>
        <%= form_with(model: Product.new ,url: cart_items_path(), class: "mb-2") do |form| %>
          <div class="form-group row mb-2">
            <%=  form.number_field :quantity, value: line_item.quantity, class: "form-control shadow rounded w-25", min: 1%>
          </div>
            <%= line_item.quantity %>
        <% end %>
      </td>
      <td><div class="content align-items-center">
            <div class="col-8">
              <strong class="f4"><%= number_to_currency(line_item.total_price) %></strong>
            </div>
          </div>
      </td>

        <td><%= button_to "Remove", cart_item_path(line_item) , method: :delete, data: {confirm: "Are you sure? " }, class: "btn btn-sm" %>
      </td>
    </tr> 
    </tbody>
  </table>  
</section>
</div>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show", @line_item %> |
  <%= link_to "Back", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<div class="container"><p style="color: green"><%= notice %></p></div>

<%= render @line_item %>

<div class="container">
  <%= link_to "Edit", edit_line_item_path(@line_item) %> |
  <%= link_to "Back", line_items_path %>

  <%= button_to "Destroy", @line_item, method: :delete %>
</div>